### ISSUE TITLE
policy file in wrong place

### ISSUE THREAD

**Issue by muelli** [cotechde/netlify-wkd#1]
It seems the policy file is placed in the wrong location.
Currently, the code creates a file under `.well-known/policy`:

https://github.com/cotechde/netlify-wkd/blob/e3ee2c36a3ac4fb51fe02f22547e2e2b785942d1/deploy-wkd.py#L79-L82

However:

```
4.5.  Policy Flags

   For key generation and submission it is useful to tell the client
   about certain properties of the mail provider in advance.  This can
   be done with a file at the URL

     WELLKNOWN/policy
```

and

```
  The string "WELLKNOWN"
   denotes the first part of an URI specific for a domain.  In the
   examples the domain "example.org" is assumed, thus:

     WELLKNOWN := https://openpgpkey.example.org/.well-known/
                  openpgpkey/example.org

   (line has been wrapped for rendering purposes)

   or if the sub-domain "opengpgkey" does not exist (direct method):

     WELLKNOWN := https://example.org/.well-known/openpgpkey
```

So either way it's currently wrong.
For the subdomain case, the script has to parse out the domain name of the UIDs and place the file in the relevant directories. For the non-subdomain case (which is arguably not applicable here), the script should put the policy file under `.well-known/openpgpkey/policy`.

**Comment by dschuermann** [comment]
Thanks for the report. Fixed in https://github.com/cotechde/netlify-wkd/commit/fdb89b6a9d33cb525762712f5707b208a372cee5

I somehow ignored the domain part, next fix coming.

**Comment by dschuermann** [comment]
Now: https://github.com/cotechde/netlify-wkd/commit/a8d0b3167bbbdfdd4e728f2e5c42dafb114e75d4
